// Build a single-leaf SSZ Merkle proof that the EL `state_root` of a chosen
// beacon block lives inside that block's `hash_tree_root`. Cross-checks the
// EL state root against `eth_getBlockByHash` on the EL RPC, then writes:
//   - `proof-<slot>.json`              — proof + roots in JSON (for any client)
//   - `../src/fixture.nr`              — Noir fixture consumed by a TXE test
//
// Usage:
//   yarn build-proof                       # default slot 14190879
//   yarn build-proof 14190879              # by slot
//   yarn build-proof 0x8a264c...           # by beacon block root
//   yarn build-proof finalized             # any beacon API block_id
//
// Env (loaded from .env):
//   BEACON_RPC_URL    base URL for the standard Beacon API
//   EL_RPC_URL        JSON-RPC URL for the execution layer (optional cross-check)

import "dotenv/config";
import { ssz } from "@lodestar/types";
import {
  createProof,
  ProofType,
  type SingleProof,
} from "@chainsafe/persistent-merkle-tree";
import { createHash } from "node:crypto";
import { writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));

// Composed gindex of `BeaconBlock.body.execution_payload.state_root`:
//   BeaconBlock.body                    field 4 / 5  -> W=8,  gindex 12  (1100)
//   BeaconBlockBody.execution_payload   field 9 / 13 -> W=16, gindex 25  (11001)
//   ExecutionPayload.state_root         field 2 / 17 -> W=32, gindex 34  (100010)
//   concat(1100 || 1001 || 00010) = 1100100100010 = 6434
const STATE_ROOT_GINDEX = 6434n;
const EXPECTED_DEPTH = 12;

const BEACON_RPC_URL = process.env.BEACON_RPC_URL;
const EL_RPC_URL = process.env.EL_RPC_URL;

if (!BEACON_RPC_URL) {
  console.error("set BEACON_RPC_URL in ts/.env");
  process.exit(1);
}

const blockId = process.argv[2] ?? "14190879";

function bytesToHex(b: Uint8Array): string {
  return "0x" + Buffer.from(b).toString("hex");
}

async function fetchBeaconBlock(id: string): Promise<{ fork: string; data: unknown }> {
  const url = `${BEACON_RPC_URL}/eth/v2/beacon/blocks/${id}`;
  const resp = await fetch(url, { headers: { Accept: "application/json" } });
  if (!resp.ok) {
    throw new Error(`beacon API ${resp.status} ${resp.statusText}: ${await resp.text()}`);
  }
  const json = (await resp.json()) as { version: string; data: unknown };
  return { fork: json.version, data: json.data };
}

async function fetchELStateRoot(blockHash: string): Promise<string | undefined> {
  if (!EL_RPC_URL) return undefined;
  const resp = await fetch(EL_RPC_URL, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      jsonrpc: "2.0",
      id: 1,
      method: "eth_getBlockByHash",
      params: [blockHash, false],
    }),
  });
  if (!resp.ok) {
    throw new Error(`EL RPC ${resp.status}: ${await resp.text()}`);
  }
  const json = (await resp.json()) as { result?: { stateRoot?: string } };
  return json.result?.stateRoot;
}

function bytes32ToNoirArray(bytes: Uint8Array, indent: string): string {
  if (bytes.length !== 32) throw new Error(`expected 32 bytes, got ${bytes.length}`);
  const lines: string[] = [];
  for (let i = 0; i < 32; i += 8) {
    const slice = Array.from(bytes.slice(i, i + 8));
    lines.push(indent + slice.map((b) => `0x${b.toString(16).padStart(2, "0")}`).join(", ") + ",");
  }
  return "[\n" + lines.join("\n") + "\n" + indent.slice(0, -4) + "]";
}

function buildFixtureSource(args: {
  slot: number;
  fork: string;
  beaconRoot: Uint8Array;
  stateRoot: Uint8Array;
  proof: Uint8Array[];
}): string {
  const { slot, fork, beaconRoot, stateRoot, proof } = args;

  const proofEntries = proof
    .map((p) => "    " + bytes32ToNoirArray(p, "        "))
    .join(",\n");

  return `//! Auto-generated by ts/src/index.ts. DO NOT EDIT BY HAND.
//!
//! slot: ${slot}
//! fork: ${fork}
//! beacon_block_root: ${bytesToHex(beaconRoot)}
//! el_state_root:     ${bytesToHex(stateRoot)}

pub global SLOT: u64 = ${slot};

pub global IS_PLACEHOLDER: bool = false;

pub global BEACON_BLOCK_ROOT: [u8; 32] = ${bytes32ToNoirArray(beaconRoot, "    ")};

pub global EL_STATE_ROOT: [u8; 32] = ${bytes32ToNoirArray(stateRoot, "    ")};

pub global PROOF: [[u8; 32]; ${proof.length}] = [
${proofEntries},
];
`;
}

async function main() {
  console.log(`fetching beacon block ${blockId}`);
  const { fork, data } = await fetchBeaconBlock(blockId);
  console.log(`fork: ${fork}`);

  const forkSsz = (ssz as Record<string, any>)[fork];
  if (!forkSsz) {
    throw new Error(`unknown fork "${fork}"; bump @lodestar/types`);
  }
  const SignedBeaconBlock = forkSsz.SignedBeaconBlock;
  const BeaconBlock = forkSsz.BeaconBlock;

  const signed = SignedBeaconBlock.fromJson(data);
  const block = signed.message;
  const slot = Number(block.slot);

  // hash_tree_root(BeaconBlock) — this is the trusted root we verify against.
  const beaconRoot: Uint8Array = BeaconBlock.hashTreeRoot(block);
  const beaconRootHex = bytesToHex(beaconRoot);
  console.log(`slot: ${slot}`);
  console.log(`beacon block root: ${beaconRootHex}`);

  const elStateRoot: Uint8Array = block.body.executionPayload.stateRoot;
  const elStateRootHex = bytesToHex(elStateRoot);
  const elBlockHash = bytesToHex(block.body.executionPayload.blockHash);
  console.log(`EL state root:    ${elStateRootHex}`);
  console.log(`EL block hash:    ${elBlockHash}`);

  // Optional cross-check via JSON-RPC.
  if (EL_RPC_URL) {
    const elStateRootFromRpc = await fetchELStateRoot(elBlockHash);
    if (elStateRootFromRpc) {
      console.log(`EL stateRoot from JSON-RPC: ${elStateRootFromRpc}`);
      if (elStateRootFromRpc.toLowerCase() !== elStateRootHex.toLowerCase()) {
        throw new Error("EL state root from beacon SSZ disagrees with eth_getBlockByHash");
      }
      console.log("[ok] consensus payload state_root agrees with EL JSON-RPC");
    }
  }

  // Build the single-leaf proof at the composed gindex.
  const view = BeaconBlock.toView(block);
  const proof = createProof(view.node, {
    type: ProofType.single,
    gindex: STATE_ROOT_GINDEX,
  }) as SingleProof;

  if (proof.witnesses.length !== EXPECTED_DEPTH) {
    throw new Error(
      `expected proof depth ${EXPECTED_DEPTH}, got ${proof.witnesses.length}; ` +
      `the SSZ shape of BeaconBlockBody/ExecutionPayload may have changed in fork ${fork}`,
    );
  }
  if (Buffer.compare(proof.leaf, elStateRoot) !== 0) {
    throw new Error("proof leaf doesn't match the EL state root — wrong gindex?");
  }

  // Re-verify byte-for-byte with the same algorithm the Noir verifier runs.
  let node = Buffer.from(proof.leaf);
  let index = STATE_ROOT_GINDEX;
  for (const sibling of proof.witnesses) {
    const buf = Buffer.alloc(64);
    if ((index & 1n) === 1n) {
      buf.set(sibling, 0);
      buf.set(node, 32);
    } else {
      buf.set(node, 0);
      buf.set(sibling, 32);
    }
    node = createHash("sha256").update(buf).digest();
    index >>= 1n;
  }
  if (index !== 1n) throw new Error(`bad gindex traversal: index=${index}`);
  if (Buffer.compare(node, beaconRoot) !== 0) {
    throw new Error(`manual verify failed: ${bytesToHex(node)} != ${beaconRootHex}`);
  }
  console.log("[ok] manual verify (matches Noir verifier algorithm) passed");

  // JSON proof for any future client.
  const jsonOut = {
    slot,
    fork,
    beacon_block_root: beaconRootHex,
    el_state_root: elStateRootHex,
    el_block_hash: elBlockHash,
    gindex: Number(STATE_ROOT_GINDEX),
    depth: proof.witnesses.length,
    proof: proof.witnesses.map((w) => bytesToHex(w)),
  };
  const jsonPath = resolve(HERE, "..", `proof-${slot}.json`);
  writeFileSync(jsonPath, JSON.stringify(jsonOut, null, 2));
  console.log(`wrote ${jsonPath}`);

  // Noir fixture consumed by the TXE test in src/main.nr.
  const fixtureSrc = buildFixtureSource({
    slot,
    fork,
    beaconRoot,
    stateRoot: elStateRoot,
    proof: proof.witnesses,
  });
  const fixturePath = resolve(HERE, "..", "..", "src", "fixture.nr");
  writeFileSync(fixturePath, fixtureSrc);
  console.log(`wrote ${fixturePath}`);

  console.log("\nnext: cd .. && aztec test --exact verify_real_proof");
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
