// Build a single-leaf SSZ Merkle proof that the EL `state_root` of a chosen
// beacon block lives inside that block's `hash_tree_root`. Cross-checks the
// EL state root against `eth_getBlockByHash` on the EL RPC, then writes:
//   - `proof-<slot>.json`              — proof + roots in JSON (for any client)
//   - `../src/fixture.nr`              — Noir fixture consumed by a TXE test
//   - `../bench/Prover.toml`           — inputs for the standalone bench crate
//
// Usage:
//   yarn build-proof                       # default slot 14190879
//   yarn build-proof 14190879              # by slot
//   yarn build-proof 0x8a264c...           # by beacon block root
//   yarn build-proof finalized             # any beacon API block_id
//
// Env (loaded from .env):
//   BEACON_RPC_URL    base URL for the standard Beacon API
//   EL_RPC_URL        JSON-RPC URL for the execution layer (optional cross-check)

import "dotenv/config";
import { getClient } from "@lodestar/api";
import { config } from "@lodestar/config/default";
import {
  createProof,
  ProofType,
  type SingleProof,
} from "@chainsafe/persistent-merkle-tree";
import { type SignedBeaconBlock } from "@lodestar/types";
import {
  ForkName,
  isForkPostBellatrix,
  type ForkPostBellatrix,
  type ForkPreGloas,
} from "@lodestar/params";

type ForkWithExecutionPayload = ForkPostBellatrix & ForkPreGloas;

function hasExecutionPayload(fork: ForkName): fork is ForkWithExecutionPayload {
  return isForkPostBellatrix(fork) && fork !== ForkName.gloas;
}
import { createPublicClient, http, type Hex } from "viem";
import { mainnet } from "viem/chains";
import { createHash } from "node:crypto";
import { writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));

// Composed gindex of `BeaconBlock.body.execution_payload.state_root`:
//   BeaconBlock.body                    field 4 / 5  -> W=8,  gindex 12  (1100)
//   BeaconBlockBody.execution_payload   field 9 / 13 -> W=16, gindex 25  (11001)
//   ExecutionPayload.state_root         field 2 / 17 -> W=32, gindex 34  (100010)
//   concat(1100 || 1001 || 00010) = 1100100100010 = 6434
const STATE_ROOT_GINDEX = 6434n;
const EXPECTED_DEPTH = 12;

const BEACON_RPC_URL = process.env.BEACON_RPC_URL;
const EL_RPC_URL = process.env.EL_RPC_URL;

if (!BEACON_RPC_URL) {
  console.error("set BEACON_RPC_URL in ts/.env");
  process.exit(1);
}

const blockId = process.argv[2] ?? "14190879";

const beacon = getClient(
  {
    baseUrl: BEACON_RPC_URL,
    globalInit: { responseWireFormat: "json" },
  },
  { config },
);
const el = EL_RPC_URL
  ? createPublicClient({ chain: mainnet, transport: http(EL_RPC_URL) })
  : null;

function bytesToHex(b: Uint8Array): Hex {
  return `0x${Buffer.from(b).toString("hex")}`;
}

function bytes32ToNoirArray(bytes: Uint8Array, indent: string): string {
  if (bytes.length !== 32) throw new Error(`expected 32 bytes, got ${bytes.length}`);
  const lines: string[] = [];
  for (let i = 0; i < 32; i += 8) {
    const slice = Array.from(bytes.slice(i, i + 8));
    lines.push(indent + slice.map((b) => `0x${b.toString(16).padStart(2, "0")}`).join(", ") + ",");
  }
  return "[\n" + lines.join("\n") + "\n" + indent.slice(0, -4) + "]";
}

interface FixtureArgs {
  slot: number;
  fork: ForkName;
  beaconRoot: Uint8Array;
  stateRoot: Uint8Array;
  proof: Uint8Array[];
}

function buildFixtureSource({ slot, fork, beaconRoot, stateRoot, proof }: FixtureArgs): string {
  const proofEntries = proof
    .map((p) => "    " + bytes32ToNoirArray(p, "        "))
    .join(",\n");

  return `//! Auto-generated by ts/src/index.ts. DO NOT EDIT BY HAND.
//!
//! slot: ${slot}
//! fork: ${fork}
//! beacon_block_root: ${bytesToHex(beaconRoot)}
//! el_state_root:     ${bytesToHex(stateRoot)}

pub global SLOT: u64 = ${slot};

pub global IS_PLACEHOLDER: bool = false;

pub global BEACON_BLOCK_ROOT: [u8; 32] = ${bytes32ToNoirArray(beaconRoot, "    ")};

pub global EL_STATE_ROOT: [u8; 32] = ${bytes32ToNoirArray(stateRoot, "    ")};

pub global PROOF: [[u8; 32]; ${proof.length}] = [
${proofEntries},
];
`;
}

function bytesToTomlArray(b: Uint8Array): string {
  return "[" + Array.from(b).map((x) => `"0x${x.toString(16).padStart(2, "0")}"`).join(", ") + "]";
}

interface ProverTomlArgs {
  leaf: Uint8Array;
  proof: Uint8Array[];
  gindex: bigint;
  root: Uint8Array;
}

function buildProverToml({ leaf, proof, gindex, root }: ProverTomlArgs): string {
  const proofLines = proof
    .map((p) => "    " + bytesToTomlArray(p) + ",")
    .join("\n");
  return [
    `# Auto-generated by ts/src/index.ts. DO NOT EDIT BY HAND.`,
    ``,
    `gindex = "${gindex}"`,
    `leaf = ${bytesToTomlArray(leaf)}`,
    `root = ${bytesToTomlArray(root)}`,
    `proof = [`,
    proofLines,
    `]`,
    ``,
  ].join("\n");
}

async function main() {
  console.log(`fetching beacon block ${blockId}`);
  const res = await beacon.beacon.getBlockV2({ blockId });
  if (!res.ok) throw res.error;
  const { version: fork } = res.meta();
  console.log(`fork: ${fork}`);

  if (!hasExecutionPayload(fork)) {
    throw new Error(`fork ${fork} has no execution_payload on the body — proof not applicable`);
  }

  // Narrow to forks bellatrix..fulu, where `body.executionPayload` is a direct
  // child of `BeaconBlockBody`. (Gloas decouples execution into payloadAttestations.)
  const signed = res.value() as SignedBeaconBlock<ForkWithExecutionPayload>;
  const block = signed.message;
  const slot = Number(block.slot);

  const sszForFork = config.getPostBellatrixForkTypes(block.slot);
  // hash_tree_root(BeaconBlock) — this is the trusted root we verify against.
  const beaconRoot = sszForFork.BeaconBlock.hashTreeRoot(block);
  const beaconRootHex = bytesToHex(beaconRoot);
  console.log(`slot: ${slot}`);
  console.log(`beacon block root: ${beaconRootHex}`);

  const elStateRoot = block.body.executionPayload.stateRoot;
  const elStateRootHex = bytesToHex(elStateRoot);
  const elBlockHash = bytesToHex(block.body.executionPayload.blockHash);
  console.log(`EL state root:    ${elStateRootHex}`);
  console.log(`EL block hash:    ${elBlockHash}`);

  // Optional cross-check via the typed EL JSON-RPC client.
  if (el) {
    const elBlock = await el.getBlock({ blockHash: elBlockHash });
    console.log(`EL stateRoot from JSON-RPC: ${elBlock.stateRoot}`);
    if (elBlock.stateRoot.toLowerCase() !== elStateRootHex.toLowerCase()) {
      throw new Error("EL state root from beacon SSZ disagrees with eth_getBlockByHash");
    }
    console.log("[ok] consensus payload state_root agrees with EL JSON-RPC");
  }

  // Build the single-leaf proof at the composed gindex.
  const view = sszForFork.BeaconBlock.toView(block);
  const proof = createProof(view.node, {
    type: ProofType.single,
    gindex: STATE_ROOT_GINDEX,
  }) as SingleProof;

  if (proof.witnesses.length !== EXPECTED_DEPTH) {
    throw new Error(
      `expected proof depth ${EXPECTED_DEPTH}, got ${proof.witnesses.length}; ` +
      `the SSZ shape of BeaconBlockBody/ExecutionPayload may have changed in fork ${fork}`,
    );
  }
  if (Buffer.compare(proof.leaf, elStateRoot) !== 0) {
    throw new Error("proof leaf doesn't match the EL state root — wrong gindex?");
  }

  // Re-verify byte-for-byte with the same algorithm the Noir verifier runs.
  let node = Buffer.from(proof.leaf);
  let index = STATE_ROOT_GINDEX;
  for (const sibling of proof.witnesses) {
    const buf = Buffer.alloc(64);
    if ((index & 1n) === 1n) {
      buf.set(sibling, 0);
      buf.set(node, 32);
    } else {
      buf.set(node, 0);
      buf.set(sibling, 32);
    }
    node = createHash("sha256").update(buf).digest();
    index >>= 1n;
  }
  if (index !== 1n) throw new Error(`bad gindex traversal: index=${index}`);
  if (Buffer.compare(node, beaconRoot) !== 0) {
    throw new Error(`manual verify failed: ${bytesToHex(node)} != ${beaconRootHex}`);
  }
  console.log("[ok] manual verify (matches Noir verifier algorithm) passed");

  // JSON proof for any future client.
  const jsonOut = {
    slot,
    fork,
    beacon_block_root: beaconRootHex,
    el_state_root: elStateRootHex,
    el_block_hash: elBlockHash,
    gindex: Number(STATE_ROOT_GINDEX),
    depth: proof.witnesses.length,
    proof: proof.witnesses.map((w) => bytesToHex(w)),
  };
  const jsonPath = resolve(HERE, "..", `proof-${slot}.json`);
  writeFileSync(jsonPath, JSON.stringify(jsonOut, null, 2));
  console.log(`wrote ${jsonPath}`);

  // Noir fixture consumed by the TXE test in src/main.nr.
  const fixtureSrc = buildFixtureSource({
    slot,
    fork,
    beaconRoot,
    stateRoot: elStateRoot,
    proof: proof.witnesses,
  });
  const fixturePath = resolve(HERE, "..", "..", "src", "fixture.nr");
  writeFileSync(fixturePath, fixtureSrc);
  console.log(`wrote ${fixturePath}`);

  // Prover.toml for the standalone bench crate (../../bench/Prover.toml).
  const proverTomlPath = resolve(HERE, "..", "..", "bench", "Prover.toml");
  writeFileSync(proverTomlPath, buildProverToml({
    leaf: elStateRoot,
    proof: proof.witnesses,
    gindex: STATE_ROOT_GINDEX,
    root: beaconRoot,
  }));
  console.log(`wrote ${proverTomlPath}`);

  console.log("\nnext:");
  console.log("  aztec test --exact verify_real_proof          # in-contract verify");
  console.log("  cd bench && nargo execute && \\");
  console.log("    bb prove --scheme ultra_honk -b target/merkle_bench.json \\");
  console.log("                                 -w target/merkle_bench.gz -o target/");
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
